### ISSUE TITLE
Volume stays in Degraded State

### ISSUE THREAD

**Issue by phal0r** [rancher/longhorn#412]
Hi guys,

we have a volume, that stays in degraded state and won't recover. Detach/Reattach doesn't help. Snapshots and Backups are not possible and with the following error:

```
time="2019-02-25T14:31:03Z" level=error msg="Error in request: Invalid name volume-snap-095d9284-6c11-45ab-8350-e950fbebdc15.img does not match pattern: volume-head-(\\d)+.img"
10.42.1.221 - - [25/Feb/2019:14:31:03 +0000] "POST /v1/replicas/1?action=snapshot HTTP/1.1" 500 259
```

Is there somthing we can do?

**Comment by yasker** [comment]
Something seems wrong with one of the replica. Can you send me the support bundle?

**Comment by phal0r** [comment]
I have attached a picture and added additional information on this comment: https://github.com/rancher/longhorn/issues/411#issuecomment-467131850

What should be included in the support bundle? I am stuck on 0.3.3 for now.

**Comment by yasker** [comment]
All the managers' log and the log for all the engines of the volume (<volumename>-e-xxx and <volumename>-r-xxx) would help.

This looks like there is a replica was interrupted somehow didn't finish the rebuild. Maybe similar to #413

**Comment by phal0r** [comment]
@yasker 
Robert sent you all the logs of the managers and volumes related to issue #411. Thanks for the investigation and all the information. From what I understand, you have a good feeling, what happened and how it can be prevented the next time. Right now, we have another volume, that is exactly in the same state. I dind't change anything here. Is there anything we can do here to recover the volume?

**Comment by yasker** [comment]
@phal0r I am looking into this issue but need a bit extra information. I have the log already, can you send me the list of files in the replica directory (you can find the node and directory in the volume detail page), as well as the content of all file with suffix `.meta`? I think one metadata file somehow got wrong in the replica `pvc-b4db5165-cb2d-11e8-ad59-4ed6ddea6d45-r-2cdf8e7a`. I want to compare it with other replicas of the volume `pvc-b4db5165-cb2d-11e8-ad59-4ed6ddea6d45`

**Comment by yasker** [comment]
I am able to reproduce the issue using the following steps:
1. Attach the volume.
2. Reduce the replica count to 1 for the volume.
3. Delete all the replicas except one.
4. Make a backup of the volume
5. Kill the replica pod using `kubectl delete`.
6. The volume would be detached automatically. Then salvage the volume, choose the only replica available.
7. Attach the volume again.
8. Increase replica count to 2.

The rebuild will never finish. The error would be triggered when a snapshot is attempted.

```
time="2019-03-08T02:18:35Z" level=info msg="Snapshotting [a2c90500-7e1f-432d-acb3-d3a06a199942] volume, user created false, created time 2019-03-08T02:18:35Z, labels map[]"
time="2019-03-08T02:18:35Z" level=error msg="Error in request: Invalid name volume-snap-b4928cd6-e7ce-49d9-b501-d47242434ddf.img does not match pattern: volume-head-(\\d)+.img"
```

**Comment by yasker** [comment]
The volume restoration steps as below. In general, we will create a new volume contains the exact information as the old one, and able to perform snapshot/backup.

1. Noted the working replica path (`origin_replica_path`) and node (`origin_replica_node`), then detach the origin volume (`old_vol`)
2. Create a new volume (`new_vol`), with exactly the same size as `old_vol`, but only 1 replica, and attach it to any node.
3. After `new_vol` become healthy, noted the replica path (`new_replica_path`) and node (`new_replica_node`), then detach the volume.
4. Copy the content of `origin_replica_node`:`origin_replica_path` to `new_replica_node`:`new_replica_path`
5. Run `cat volume.meta` in the new_replica directory, you would see `Head` is `volume-snap-xxxx` instead of `volume-head-xxxx`. Note `volume-snap-xxx` as `wrong_head`
6. Remove any `volume-head-xxxx` in the new_replica dir. Noted the name as `correct_head`
	1. If any data contains in the `volume-head-xxxx` (you can check with `du volume-head-xxxx.img`, those data would be **lost**. Though those data don't exist in the live volume (means if you're reading/writing the volume correctly now, you won't able to see those data anyway), so mostly it should be fine.
7. Rename `wrong_head`.img and `wrong_head`.img.meta to `correct_head`.img and `correct_head`.img.meta
8. Modify volume.meta "Head" to use `correct_head`.img instead of `wrong_head`.img
9. Run `sync` on the node.
10. Attach the `new_vol`, test if everything is fine.

After restoration, you can run a checksum against the `old_vol` and `new_vol`. They're should be exactly the same.

The fix will come with v0.4.1 release.

**Comment by yasker** [comment]
@phal0r fix has been merged in v0.4.1 release. Let me know if the volume recovery works.

**Comment by yasker** [comment]
Close the issue for now since the fix has been merged in v0.4.1.

**Comment by phal0r** [comment]
@yasker 
Thanks for the details. Unfortunately your instructions are not applicable via ui, since the minimum amount of replicas allowed are 2. I used `docker cp` to copy all content out of the degraded volume, generated a new one and copied everything to the new volume and just changed it in the volume mount of our workload. This has worked for me. Backups are now possible again and there are 3 healthy replicas. Yay!

**Comment by phal0r** [comment]
@yasker 
Problem persists with 0.4.1. Even worse, volumes in this state create now Snapshots every seconds and produce high load.

**Comment by yasker** [comment]
@phal0r Have the engines upgraded to v0.4.1 as well?

**Comment by phal0r** [comment]
Yes, but as I already wrote on Slack, the Cluster is totally unstable and behaves randomly, so it is unclearly what the root cause could be.
