### ISSUE TITLE
Degraded volume not replicating

### ISSUE THREAD

**Issue by NchemIcaLS** [rancher/longhorn#419]
After restarting some of the nodes there is only one healthy replica remaining. This replica is not being replicated to the other nodes. This may be related to #412 or #350. I attempted to delete the unhealthy replicas, detach and attach the volume and change the engine image without success. Would appreciate some advice before I try anything else and the data is gone.

```
2/26/2019 6:11:20 PM time="2019-02-26T17:11:20Z" level=warning msg="Error syncing Longhorn engine longhorn-system/pvc-f7218fa5ec2a11e8-e-c1f4c4d5: fail to sync engine for longhorn-system/pvc-f7218fa5ec2a11e8-e-c1f4c4d5: fail to start rebuild for pvc-f7218fa5ec2a11e8-r-ad6a7753 of pvc-f7218fa5ec2a11e8-e-c1f4c4d5: timed out waiting for the condition"
2/26/2019 6:11:20 PM time="2019-02-26T17:11:20Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"pvc-f7218fa5ec2a11e8-e-c1f4c4d5\", UID:\"f7f809ad-ec2a-11e8-af7d-000c29dc70ce\", APIVersion:\"longhorn.rancher.io/v1alpha1\", ResourceVersion:\"27622422\", FieldPath:\"\"}): type: 'Normal' reason: 'Rebuilding' Start rebuilding replica pvc-f7218fa5ec2a11e8-r-fce6bde9 with IP 10.42.0.159 for pvc-f7218fa5ec2a11e8"
2/26/2019 6:11:20 PM time="2019-02-26T17:11:20Z" level=error msg="Failed rebuilding 10.42.0.159 of pvc-f7218fa5ec2a11e8: failed to add replica address='tcp://10.42.0.159:9502' to controller 'pvc-f7218fa5ec2a11e8': Failed to execute: /var/lib/rancher/longhorn/engine-binaries/rancher-longhorn-engine-v0.4.0/longhorn [--url http://10.42.0.158:9501 add tcp://10.42.0.159:9502], output time=\"2019-02-26T17:11:20Z\" level=info msg=\"Adding replica tcp://10.42.0.159:9502 in WO mode\" \ntime=\"2019-02-26T17:11:20Z\" level=fatal msg=\"Error running add replica command: Bad response: 500 500 Internal Server Error: {\\\"actions\\\":{},\\\"code\\\":\\\"Server Error\\\",\\\"detail\\\":\\\"\\\",\\\"links\\\":{\\\"self\\\":\\\"http://10.42.0.158:9501/v1/replicas\\\"},\\\"message\\\":\\\"Replica must be closed, Can not add in state: open\\\",\\\"status\\\":500,\\\"type\\\":\\\"error\\\"}\\n\" \n, error exit status 1"
2/26/2019 6:11:20 PM time="2019-02-26T17:11:20Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"pvc-f7218fa5ec2a11e8-e-c1f4c4d5\", UID:\"f7f809ad-ec2a-11e8-af7d-000c29dc70ce\", APIVersion:\"longhorn.rancher.io/v1alpha1\", ResourceVersion:\"27622422\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedRebuilding' Failed rebuilding replica with IP 10.42.0.159: failed to add replica address='tcp://10.42.0.159:9502' to controller 'pvc-f7218fa5ec2a11e8': Failed to execute: /var/lib/rancher/longhorn/engine-binaries/rancher-longhorn-engine-v0.4.0/longhorn [--url http://10.42.0.158:9501 add tcp://10.42.0.159:9502], output time=\"2019-02-26T17:11:20Z\" level=info msg=\"Adding replica tcp://10.42.0.159:9502 in WO mode\" \ntime=\"2019-02-26T17:11:20Z\" level=fatal msg=\"Error running add replica command: Bad response: 500 500 Internal Server Error: {\\\"actions\\\":{},\\\"code\\\":\\\"Server Error\\\",\\\"detail\\\":\\\"\\\",\\\"links\\\":{\\\"self\\\":\\\"http://10.42.0.158:9501/v1/replicas\\\"},\\\"message\\\":\\\"Replica must be closed, Can not add in state: open\\\",\\\"status\\\":500,\\\"type\\\":\\\"error\\\"}\\n\" \n, error exit status 1"
2/26/2019 6:11:20 PM time="2019-02-26T17:11:20Z" level=error msg="Removed failed rebuilding replica 10.42.0.159 of pvc-f7218fa5ec2a11e8"
```
I can send the support bundle if needed. If so where should I send it?

**Comment by yasker** [comment]
@NchemIcaLS You can send the support bundle to me at my email (listed in my profile), or on Slack @yasker

**Comment by yasker** [comment]
@NchemIcaLS I've received the support bundle.

There is an issue in that volume: "Too many snapshots created". The snapshot limit is around 200. There was a related issue we fixed in #253 . But since you're running v0.4.0, this can caused by something else.
```
2019-02-26T17:12:18.203809066Z time="2019-02-26T17:12:18Z" level=error msg="Error in request: Too many snapshots created" 
2019-02-26T17:12:18.204134364Z 10.42.1.214 - - [26/Feb/2019:17:12:18 +0000] "POST /v1/replicas HTTP/1.1" 500 171
2019-02-26T17:12:48.321996606Z time="2019-02-26T17:12:48Z" level=info msg="Connecting to remote: 10.42.2.233:9502"
```

Can you try the following steps:
1. Make a backup of the current volume.
2. Reduce the replica count of the volume to the number of current healthy replicas.
    2.1 If I read it correctly, you have only one replica `pvc-8cfc741eec1a11e8-r-61c3c623` in RW state of the volume. So you can reduce the number to 1.
3. Delete the replicas stuck in the rebuild state. Now you should have only healthy replicas running.
4. Delete the snapshots manually except for the latest e.g. 25 snapshots.
5. Increase the replica count of the volume by 1. Wait for the rebuild to complete.
6. Repeat step 5 till you get desired replica count number for the volume.

There was a limited amount of log before `Too many snapshots created` message. If anything abnormal happened with the volume?

**Comment by NchemIcaLS** [comment]
I didn't realize there were that many snapshots. The backup settings are set to retain 7 for the past week (backup 1x each day) and 12 for the year (backup 1x each month). This volume has only existed for 3 months so even if I made a snapshot every day that would only be around 100 snapshots. Is there a reason there are this many snapshots? Do I need to configure something differently?

The snapshots also only appear on the volume details. Only 8 snapshots are showing under the backup page when selecting the same volume.

After manually deleting several backups I was able to backup the current state. However, I can't reduce the replica count because of the following error:
```
volume must be healthy to update replica count
```

I have 4 more volumes that are in the exact same state (they are not attached since I was concerned about the data). Nothing abnormal happened except that the Kubernetes cluster is on premise and the servers were restarted causing individual nodes to temporarily drop out; however longhorn has survived this in the past, even a power outage.

**Comment by NchemIcaLS** [comment]
I managed to get 3/4 volumes back to healthy by deleting snapshots and then de/re attaching them. However pvc-85d77fd9ea6f11e8 is still not rebuilding even after deleting some snapshots. I tried to analyze the logs but couldn't find out why. I sent you another email with a new support bundle.

**Comment by yasker** [comment]
@NchemIcaLS 

Sorry, I forgot about the replica count update limitation...

Seems `pvc-85d77fd9ea6f11e8-r-e5e50d90` is in trouble. We have seen this before we haven't found the root cause of this. I would file a separate issue for this.

> 2019-02-26T21:42:21.051086295Z time="2019-02-26T21:42:21Z" level=error msg="Error in request: Invalid name volume-snap-c-wyw6oz-f0590eb8.img does not match pattern: volume-head-(\\d)+.img"

If you delete the replica `pvc-85d77fd9ea6f11e8-r-e5e50d90`(after backup the volume), the rebuild should resume.

Regarding snapshots and backups, there is nothing wrong with your setup. Snapshots are different from backups in Longhorn. Snapshots colocated with the volume data, so if volume lost, the snapshots of the volume would be lost with it as well. But backups are located outside Longhorn, so if volume lost, there is no impact on backups since it's stored outside Longhorn. Longhorn can still retrieve the backups and restore the volume.

The number limitation only applies to the snapshots, not backups. You can have as many backups as you want.

If you've created the volume before Longhorn v0.3.3, there was a bug (#253) that would continuously create system snapshot for rebuilding purpose, so it can result in `Too many snapshots` error. That state will be with the volume until you delete the snapshots and free up the slots. There also can be another bug we haven't found yet result in the same thing. I will perform more test in the lab to see if it can happen in any other situation.

**Comment by NchemIcaLS** [comment]
Thank you for explaining the difference between snapshots and backups. That makes sense now. 

Unfortunately that is replica is the only healthy one so after deleting it the volume is essentially gone as there is no data now. I also couldn't make a backup of that last replica as the entire volume would immediately crash and go into a faulted state. But thanks to the backups I had scheduled every day I was easily able to restore to a backup from the previous day. The data lost was negligible so this wasn't a problem. I was pleasantly surprised how well the backups worked and a great feeling that there are so many fail-overs even if something happens.

Thanks again for the support!

**Comment by yasker** [comment]
@NchemIcaLS Oh, sorry, I didn't notice `pvc-85d77fd9ea6f11e8-r-e5e50d90` is the only RW replica in the volume. Well, that explains it.

The replica "Invalid name" issue will be tracked at #412 .
